#!/usr/bin/env bash

function _boxcutter_ubuntu_profile {
  local shome="${_boxcutter_ubuntu_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"
  
}

_boxcutter_ubuntu_profile
